### ISSUE TITLE
XP12 Support.

### ISSUE THREAD

**Issue by bdzerr** [xEtarusx/xplane-gateway-downloader#2]
Hiya, can 12 be added to the list of valid versions if LR has separated 11/12 tags that is, the mass update your little tool has is a time saver id like to keep :)

**Comment by xEtarusx** [comment]
Hi @Josh4471,
I checked it and the problem currently lies in the official API of Laminar. They do not provide any XP12 version in that list. Unfortunately that means that the application does not know the current airport version which are included in XP12. If you choose 11.55 everything newer will be updated, but most of the updates are already included in XP12.

We'll have to wait until Laminar updates the API response and they include XP12 there.

Regards,
Etarus

**Comment by xEtarusx** [comment]
I opened a xplane gateway bug report (XSG-14027). When they have any news if and when the 12.XX versions will be listed I'll let you know.

**Comment by xEtarusx** [comment]
@Josh4471 The developers at Laminar Research now added the version 12.04 to the releases. You can now set your version to 12.04 to let the downloader know the currently released airport versions.
